### PR TITLE
Music album and genre class

### PR DESCRIPTION
**Pull request by Owusu-Desmond**
In this pull request, I did the following

- [ ] I Created a MusicAlbum class in a separate .rb file.
- [ ] All MusicAlbum class properties visible in the diagram have been set up in the constructor method.
- [ ] I Implement the following methods to the music album class
  - can_be_archived?() in the MusicAlbum class
    which overrides the method from the parent class
    and it returns true if the parent's method returns true AND if on_spotify equals true
    otherwise, it returns false
- [ ] I created a `Genre` class with an association to the Item class (in a separate .rb file).
- [ ] I added Genre class properties visible in the diagram that has been set up in the constructor method.
- [ ] I implemented the following methods
    - add_item method in the Genre class
        - it takes an instance of the Item class as an input
        - that adds the input item to the collection of items
        - that self as a property of the item object
- [ ] I added the following additional methods to `genre` and music_`album class` 
   - List all music albums
   - List all genres
   - Add a music album

### CODE REVIEW

**Review by gak92 — APPROVED** [review]
Hi @Owusu-Desmond , 

Your task is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Owusu-Desmond** [comment]
Hi @Mesi21 , you need to add your review to this pull request

**Review by Mesi21 — APPROVED** [review]
Hi @Owusu-Desmond , 

Your task is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Owusu-Desmond** [comment]
Hi @gak92 and @Mesi21,

I have made changes to the `item.rb` can you please check

**Comment by gak92** [comment]
@Owusu-Desmond,
It looks OK. You can merge it.

**Pull request merged**
